site_tutorial/mysite/main/urls.py
from django.urls import path
from . import views


app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("songs/", views.get_tracks, name="get_tracks"),
    path("songs/<str:track_id>", views.get_song_details, name="get_song_details"),
    path("rate_song/<str:track_title>/", views.rate_song, name="rate_song"),
    path("chart/<str:chart_name>", views.get_chart, name="get_chart"),
    path("user_chart/", views.get_user_chart, name="get_user_chart"),
    path("friend_chart/", views.get_friend_chart, name="get_friend_chart"),
    path("chart_track/<str:track_id>", views.get_chart_song_details, name="get_chart_song_details"),
    path("addToPlaylist/<str:track_id>", views.add_to_playlist, name="add_to_playlist"),
    path("register/", views.register, name="register"),
    path("update/", views.update_profile, name="update_profile"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("friends/", views.friends, name="friends"),
    path("send_friend_request/", views.send_friend_request, name='send_friend_request'),
    path("accept_friend_request/<int:requestID>/", views.accept_friend_request, name='accept friend request'),
]

site_tutorial/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('main.urls')),
    path('admin/', admin.site.urls),
]

site_tutorial/mysite/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.

# this class may or may not be in use...
class UserStat(models.Model):
    first_name = models.CharField(max_length=100, default='first')
    last_name = models.CharField(max_length=100, default='last')
    username = models.CharField(max_length=200, default='user')

    def __str__(self):
        return self.username


# this class links the userform to profileform for storing spotify username for data access
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    spotify_username = models.CharField(help_text="Spotify Username", max_length=200, blank=True)
    playlist_id = models.CharField(max_length=200, blank=True)
    friends = models.ManyToManyField("Profile", blank=True)

    def __str__(self):
        return self.user.username


class Friend_Request(models.Model):
    from_user = models.ForeignKey(Profile, related_name='from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(Profile, related_name='to_user', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('from_user', 'to_user')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class SongStat(models.Model):
    artist = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    artist_id = models.CharField(max_length=200, default='none')
    track_id = models.CharField(max_length=200, default='none')
    img_url = models.CharField(max_length=200, default='none')

    def __str__(self):
        return self.artist


class TrackStat(models.Model):
    user = models.IntegerField(blank=True, null=True)
    artist = models.CharField(max_length=200, default='none')
    title = models.CharField(max_length=200, default='none')
    track_id = models.CharField(max_length=200, default='none')
    img_url = models.CharField(max_length=200, default='none')
    release_date = models.CharField(max_length=200, default='none')
    # duration = models.BigIntegerField()
    duration = models.DecimalField(max_digits=5, decimal_places=2)
    snippet = models.URLField(max_length=200, default='none')
    rating = models.IntegerField(default=0, blank=True, null=True,
                                 validators=[
                                     MaxValueValidator(5),
                                     MinValueValidator(1)
                                 ])

    def __str__(self):
        return self.title


class ChartStat(models.Model):
    user = models.IntegerField(blank=True, null=True)
    artist = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    rank = models.BigIntegerField(default=0)
    track_id = models.CharField(max_length=200, default='none')

    def __str__(self):
        return self.title


class ChartStatUser(models.Model):
    artist = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    rank = models.BigIntegerField(default=0)
    track_id = models.CharField(max_length=200, default='none')

    def __str__(self):
        return self.title

site_tutorial/mysite/main/forms.py
from django import forms
from .models import Profile, Friend_Request
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

        def save(self, commit=True):
            user = super(NewUserForm, self).save(commit=False)
            user.email = self.cleaned_data["email"]
            if commit:
                user.save()
            return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('spotify_username',)


class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend_Request
        fields = ['from_user', 'to_user']

site_tutorial/mysite/main/views.py
from django.shortcuts import render, redirect
from .models import UserStat, SongStat, TrackStat, ChartStat, ChartStatUser, Friend_Request, Profile
from .forms import NewUserForm, ProfileForm, FriendForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, authenticate, login, get_user_model
from django.contrib import messages
import spotipy
import billboard
from spotipy.oauth2 import SpotifyOAuth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from scipy.stats import zscore
from scipy.spatial.distance import pdist, squareform

scaler = StandardScaler()

chart_df = pd.DataFrame()

scope = 'user-library-read'
myClientId = "2344bd804b504053be8587dc0a2a6a83"
mySecret = "98ea96fd09224098bacebb6e9756c4de"
myRedirect = "http://localhost:8888/callback/"

from django.db import transaction


def homepage(request):
    # billboard hot 100 display
    chart = billboard.ChartData('hot-100')
    chart_collection = {}

    # delete old pulls of hot 100
    # TrackStat.objects.all().delete()
    # ChartStat.objects.all().delete()

    # for idx, c in enumerate(chart):
    #    chart_data = ChartStat(
    #        artist=c.artist,
    #        title=c.title,
    #        rank=idx + 1
    #    )
    #    chart_data.save()
    #    chart_collection = ChartStat.objects.all()

    # current_user = request.user
    # if request.user.is_authenticated:
    # print(current_user.username)
    # print(current_user.select_related('profile'))
    # print(request.user.profile.spotify_username)

    # print(Profile.objects.all())
    # print(Friend_Request.objects.all())

    # get friends list
    friends = []
    if request.user.is_authenticated:
        user_profile = Profile.objects.get(user=request.user.id)
        # print("user_profile: ", user_profile)
        friends = user_profile.friends.all()
        # print("friends: ", friends)

    return render(request=request,
                  template_name='main\home3.html',
                  context={  # "ChartStats": ChartStat.objects.all,
                      "allusers": Profile.objects.all,
                      "all_friend_requests": Friend_Request.objects.all,
                      "friends": friends})


@login_required
def send_friend_request(request):
    to_user_get = "not logged in"

    if request.method == "POST":
        friend_request_form = FriendForm(request.POST)
        # print("friend_form: ", friend_request_form)
        # print("to_user", request.POST.get("users"))
        # print("from_user", request.POST.get("senderId"))

        if friend_request_form.is_valid():
            to_user_get = friend_request_form.cleaned_data['user']
    else:
        friend_request_form = FriendForm()

    # print("to_user_get: ", to_user_get)

    # all_users = Users.objects.all()
    # User = get_user_model()
    # users = User.objects.all()
    # for user in users:
    # print(user.username)

    # print("type of post request data to user: ", type(request.POST.get("users")))

    # print("UserID: ", userID)
    from_user = request.user
    from_user_profile = Profile.objects.get(user=from_user)
    # print("type of post request data from user: ", type(from_user_profile))
    # print("from_user_profile: ", from_user_profile)
    # print("from user: ", from_user)

    # to_user = Profile.objects.get(id=userID)
    User = get_user_model()
    to_user_user = User.objects.get(username=request.POST.get("users"))
    # print
    # print("to_user_User: ", type(to_user_user))
    to_user_profile = Profile.objects.get(user=to_user_user)
    # rint("to_user_profile: ", to_user_profile)
    # print("to_user_profile type: ", type(to_user_profile))

    # print("to user: ", to_user)
    # print("to user id: ", to_user.id)
    # print("from user id: ", from_user.id)
    friend_request, created = Friend_Request.objects.get_or_create(from_user=from_user_profile, to_user=to_user_profile)
    if created:
        messages.success(request, f"Friend Request Sent!")
        return redirect("main:friends")
        # return HttpResponse('friend request sent')
    else:
        messages.error(request, f"Friend Request Already Sent!")
        return redirect("main:friends")
        # return HttpResponse('friend request was already sent')


@login_required
def accept_friend_request(request, requestID):
    friend_request = Friend_Request.objects.get(id=requestID)
    # print("request.user: ", request.user)
    # print("friend_request.to_user: ", friend_request.to_user.user)
    if friend_request.to_user.user == request.user:
        friend_request.to_user.friends.add(friend_request.from_user)
        friend_request.from_user.friends.add(friend_request.to_user)
        friend_request.delete()
        messages.success(request, f"Friend Request Accepted!")
        return redirect("main:friends")
    else:
        messages.error(request, f"Friend request not accepted")
        return redirect("main:friends")


def get_chart(request, chart_name):
    scope = 'user-library-read'
    myClientId = "2344bd804b504053be8587dc0a2a6a83"
    mySecret = "98ea96fd09224098bacebb6e9756c4de"
    myRedirect = "http://localhost:8888/callback/"
    myUsername = request.user.profile.spotify_username
    chart = billboard.ChartData(chart_name)

    # check to se if chart data for user already exists
    user_id = request.user.id
    # print("user id in get chart: ", user_id)
    # print("all previous chartstats: ", ChartStat.objects.all())
    # print("trying filter to see what we get: ", ChartStat.objects.filter(user=user_id))
    myChartStats = ChartStat.objects.filter(user=user_id)
    if myChartStats:
        # ChartStat.objects.get(user=user_id)
        # Location.objects.filter(name='Paul').first()
        # ChartStat.objects.filter(user=user_id)
        print("chartstats DO have user fields")
    else:
        print("none of the chartstats have user fields yet, assigning now")
        token = spotipy.prompt_for_user_token(myUsername, scope, myClientId, mySecret, myRedirect)

        sp = spotipy.Spotify(auth=token)
        chart_collection = {}

        # delete old pulls of chart data
        ChartStat.objects.all().delete()

        temp_df = pd.DataFrame((), columns=['id', 'title', 'all_artists', 'popularity', 'danceability', 'energy', 'key',
                                            'loudness', 'mode', 'acousticness', 'instrumentalness', 'liveness',
                                            'valence',
                                            'tempo', 'duration_ms', 'time_signature'])

        # print("df: ", df)

        for idx, c in enumerate(chart):
            # print(c.title.split(" ", 1)[0])
            shortened_artist = c.artist.split(" ", 1)[0]
            track = sp.search(q='artist:' + shortened_artist + ' track:' + c.title, type='track')
            # print(c)
            # df = pd.read_json(track['tracks']['items'][0])
            # print("artist: ", shortened_artist)
            # print(track['tracks']['items'][0])
            # print(getTopTracks(track['tracks'][0], sp))
            # print("Track Info:", track['tracks'])
            # print("\n")
            if (track['tracks']['total'] == 0):
                track_id = 'none'
            else:
                track_id = track['tracks']['items'][0]['id']
                # get chart details & audio features df
                df = get_chart_features(track_id, track, sp)
                temp_df = temp_df.append(df, ignore_index=True)
            chart_data = ChartStat(
                user=user_id,
                artist=c.artist,
                title=c.title,
                rank=idx + 1,
                track_id=track_id
            )
            chart_data.save()
            myChartStats = ChartStat.objects.filter(user=user_id)

            # print("Chart DF: ", df)
            global chart_df
            chart_df = temp_df

    return render(request=request,
                  template_name='main\chart.html',
                  context={"ChartStats": myChartStats,
                           "ChartName": chart.title})


def get_chart_features(track_id, result, sp):
    tracks_id = []
    tracks_titles = []
    tracks_artists = []
    tracks_popularity = []
    print("track id: ", track_id)
    # print(result, "\n")
    data = result['tracks']['items'][0]
    tracks_id = track_id
    tracks_titles = data['name']
    tracks_artists = data['artists'][0]['name']
    tracks_popularity = data['popularity']
    # print(data, "\n")
    features = sp.audio_features(track_id)
    features_df = pd.DataFrame(data=features, columns=features[0].keys())
    features_df['title'] = tracks_titles
    features_df['all_artists'] = tracks_artists
    features_df['popularity'] = tracks_popularity
    features_df = features_df[
        ['id', 'title', 'all_artists', 'popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',
         'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms', 'time_signature']]
    # print(features_df, "\n")
    return features_df


def get_friend_ids(user):
    out = []
    myProfile = Profile.objects.get(user=user)
    myFriends = myProfile.friends.all()
    # print("My Profile ID: ", myProfile.user.id)
    # print("My Friends: ", myProfile.friends.all())
    for friend in myFriends:
        # print("friend w id: ", friend.user.id)
        out.append(friend.user.id)

    return out


def get_friend_chart(request):
    myClientId = "2344bd804b504053be8587dc0a2a6a83"
    mySecret = "98ea96fd09224098bacebb6e9756c4de"
    myRedirect = "http://localhost:8888/callback/"
    myUsername = request.user.profile.spotify_username
    scope = 'user-top-read user-read-recently-played'

    token = spotipy.prompt_for_user_token(myUsername, scope, myClientId, mySecret, myRedirect)
    sp = spotipy.Spotify(auth=token)

    #delete user chart data

site_tutorial/mysite/main/templates/main/chart.html
{% extends 'main/header.html' %}

{% block content %}
    <div class="card-deck">

            <div class="card teal lighten-4">
                <div class="card-content black-text">
                    <span class="card-title">{{ChartName}}</span>
                    <button onclick="location.href = '/user_chart/'">User Order</button>
                    <button onclick="location.href = '/friend_chart/'">Friend Order</button>
                        <ul>
                            {% for c in ChartStats %}
                                <li>{{c.rank}}. {{c.title}} - {{c.artist|safe}}</li>

                                {% if c.track_id != 'none' %}
                                <button onclick="location.href = '/chart_track/{{c.track_id}}'">Go To Track</button>
                                {% endif %}
                                
                                <br></br> 
                            {% endfor %}
                        </ul>
                </div>
            </div>

    </div>
{% endblock %}

site_tutorial/mysite/main/templates/main/friends.html
{% extends 'main/header.html' %}
{% block content %}
<form action="{% url 'main:send_friend_request' %}"  method="POST">{% csrf_token %}
    <label for="users">Find Users:</label>
    <input type="text" id="users" name="users" autocomplete="users">
    <input type="hidden" id="senderId" name="senderId" value={{user}}>
    <script>
  $( function() {
    var availableUsers = [
        {% for user in allusers %}
            "{{user.user.username}}",
        {% endfor %}
    ];
    $( "#users" ).autocomplete({
      source: availableUsers
    });
  } );
  </script><br><br>

    <script>
        function getInputValue(){
            // Selecting the input element and get its value
            var user = document.getElementById("users").value;

            //join path and user id into format url string
            str path = "/send_friend_request/" + user.id + "/";
            return user.id;

        }
    </script>

    <input type="submit" value="Send them a Friend Request">
</form>

<div class="card-deck">

    <div class="card teal lighten-4">
        <div class="card-content black-text">
            <span class="card-title">My Friends</span>
            <div class="card-content">
                <ul class="all_users">
                    {% for friend in friends %}
                    <p>{{friend}}</p>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    {% if user.is_authenticated %}
        <div class="card teal lighten-4">
        <div class="card-content black-text">
            <span class="card-title">Friend Requests</span>
            <div class="card-content">
                {% for friend_request in all_friend_requests %}
                {% if user.username == friend_request.to_user.user.username %}
                <p>{{friend_request.from_user}} <a href="/accept_friend_request/{{friend_request.id}}/">accept friend request</a></p>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}

</div>
{% endblock %}

site_tutorial/mysite/main/templates/main/header.html
<head>
    {% load static %}
    <!-- Prism CSS -->
    <link href="{% static "tinymce/css/prism.css" %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src=
                    "https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">
    </script>

    <script src=
                    "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">
    </script>

    <link href=
                  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
          rel="stylesheet" type="text/css" />

    <style>
        .card {width:500px;
                margin: 10 auto; /* Added */
                float: none; /* Added */
                margin-bottom: 10px; /* Added */}

    </style>
</head>

<body>
    
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo">Spotify Insights</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% include 'main/includes/navbaritems.html' %}
            </ul>
        </div>
    </nav>
    
    {% include 'main/includes/messaging.html' %}
    
    <div class = "container">
        {% block content %}
        {% endblock %}
    </div>
</body>

<!-- Prism JS -->
<script src="{% static "tinymce/js/prism.js" %}"></script>

site_tutorial/mysite/main/templates/main/home.html
{% extends 'main/header.html' %}

{% block content %}
    <div class="row">
        {% for u in UserStats %}
            <div class="col s12 m6">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title">User: {{u.username}}</span>
                        <p>Name: {{u.first_name}} {{u.last_name|safe}}</p>
                    </div>
                </div>
                <button onclick="location.href = '/songs'">See Your Top Tracks</button>
            </div>
        {% endfor %}
     </div>
{% endblock %}

site_tutorial/mysite/main/templates/main/home2.html
{% extends 'main/header.html' %}

{% block content %}
    <div class="card-deck">

            <div class="card teal lighten-4">
                <div class="card-content black-text">
                    {% if user.is_authenticated %} 
                        <span class="card-title">Welcome to Spotify Insights {{user.username}}</span>
                        <br></br>
                        {% if user.profile.spotify_username %}
                            <button onclick="location.href = '/songs'">See Your Top Tracks</button>
                        {% else %}
                            <button onclick="location.href = '/update'">Connect to Spotify</button>
                        {% endif %}
                    {% else %}
                        <span class="card-title">Welcome to Spotify Insights</span>
                        <p> Please create an account to unlock your personal music insights.</p>
                        <br></br>
                        <button onclick="location.href = '/register'">Register</button>
                    {% endif %}
                </div>
            </div>


            <div class="card teal lighten-4">
                <div class="card-content black-text">
                    <span class="card-title">Billboard Hot 100</span>
                        <ul>
                            {% for c in ChartStats %}
                            <li>{{c.rank}}. {{c.title}} - {{c.artist|safe}}</li>

                            {% endfor %}
                        </ul>
                </div>
            </div>

    </div>
{% endblock %}

site_tutorial/mysite/main/templates/main/home3.html
{% extends 'main/header.html' %}
{% block content %}
    <div class="card-deck">

            <div class="card teal lighten-4">
                <div class="card-content black-text">
                    {% if user.is_authenticated %} 
                        <span class="card-title">Welcome to Spotify Insights {{user.username}}</span>
                        <br></br>
                        {% if user.profile.spotify_username %}
                            <button onclick="location.href = '/songs'">See Your Top Tracks</button>
                        {% else %}
                            <button onclick="location.href = '/update'">Connect to Spotify</button>
                        {% endif %}
                    {% else %}
                        <span class="card-title">Welcome to Spotify Insights</span>
                        <p> Please create an account to unlock your personal music insights.</p>
                        <br></br>
                        <button onclick="location.href = '/register'">Register</button>
                    {% endif %}
                </div>
            </div>


            <div class="card teal lighten-4">
                <div class="card-content black-text">
                    <span class="card-title">Billboard Hot 100</span>
                    <a href="/chart/hot-100">Interact with these tracks</a>
                </div>
            </div>

            <div class="card teal lighten-4">
                <div class="card-content black-text">
                    <span class="card-title">Top Pop</span>
                    <a href="/chart/pop-songs">Interact with these tracks</a>
                </div>
            </div>

            <div class="card teal lighten-4">
                <div class="card-content black-text">
                    <span class="card-title">Top Country</span>
                    <a href="/chart/country-songs">Interact with these tracks</a>
                </div>
            </div>
            

            <div class="card teal lighten-4">
                <div class="card-content black-text">
                    <span class="card-title">Top Rap and Hip Hop</span>
                    <a href="/chart/rap-songs">Interact with these tracks</a>
                </div>
            </div>

    </div>
{% endblock %}

site_tutorial/mysite/main/templates/main/login.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="container">
        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
            <button style="background-color:#549c5f; color:black" class="btn btn-outline-info" type="submit">Login</button>
        </form>
        Don't have an account? <a href="/register" target="blank"><strong>register here</strong></a>!
    </div>
{% endblock %}

site_tutorial/mysite/main/templates/main/profile.html
{% extends 'main/header.html' %}

{% block content %}
    <div class = "container">
        <form method="post">
            {% csrf_token %}
            {{ profile_form.as_p }}
            <button type="submit">Save changes</button>
        </form>
    </div>
{% endblock %}

site_tutorial/mysite/main/templates/main/register.html
{% extends 'main/header.html' %}

{% block content %}
    
    <div class = "container">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            {{profile_form.as_p}}

            <button style="background-color:#65c96d; color:black" class="btn btn-outline-info" type="submit">Sign Up</button>
    
        </form>
    
        If you already have an account <a href="/login" target="blank"><strong>login</strong></a> instead.                  
    </div>
{% endblock %}

site_tutorial/mysite/main/templates/main/song_info.html
{% extends 'main/header.html' %}

{% block content %}
{% for t in TrackStats %}
<div class="row">
    <div class="col s12 m7">
        <div class="card">
            <div class="card-image">
                <img src={{t.img_url}}>
            </div>
            <div class="card-content">
                <p>{{t.title}} by {{t.artist}} was released on {{t.release_date}} and is {{t.duration}} minutes long.</p>
                <br>
                {% if t.rating == 0 %}
                <p>You haven't rated this song yet. Rate it Below!</p>
                {% else %}
                <p>You've rated this song {{t.rating}} out of 5 stars</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href={{t.snippet}}> Listen </a>
                {% if c.track_id != 'none' %}
                <button onclick="location.href = '/addToPlaylist/{{ChartId}}'">Add to Playlist</button>
                {% endif %}
                <form action="/rate_song/{{t.title}}/" method="post">
                    {% csrf_token %}
                    <label for="rate_song">Rate Song: </label>
                    <input id="rate_song" type="text" name="rating" value="Enter Rating (1-5 Stars)">
                    <input type="submit" value="Update Rating">
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

site_tutorial/mysite/main/templates/main/songs.html
{% extends 'main/header.html' %}

{% block content %}
<div class="col s12 m6">
    <div class="card blue-grey darken-1">
        <div class="card-content white-text">
        <span class="card-title">Your Saved Tracks</span>
        {% for s in SongStats %}
        <a onclick="location.href = '/songs/{{s.track_id}}'" >
          <div class="card white lighten-2">
            <ul class="list-group list-group-flush">
                <li>{{s.title}} - {{s.artist|safe}}</li>
            </ul>
          </div>
          </a>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

site_tutorial/mysite/main/templates/main/songs2.html
{% extends 'main/header.html' %}

{% block content %}
{% for s in SongStats %}
<div class="container-fluid">
<div class = "row justify-content-center">
    <div class="col d-flex justify-content-center">
        <a onclick="location.href = '/songs/{{s.track_id}}'" >
        <div class="card" style="width:300px">
            <div class="card-image">
            <img src={{s.img_url}} width="300" height="300" alt="{{s.artist}}'s album">
        </div>
        </a>
    </div>
</div>
</div>
{% endfor %}
{% endblock %}